SELECT 
        DBA.USERNAME,
        UM.PASSWORD,
        UA.FIRSTNAME
FROM 
        DBA_USERS DBA, DBADMINS.USER_MASTER UM, RMS13PRD.USER_ACCOUNTS UA
WHERE 
        DBA.USERNAME = UM.USERNAME
    AND
        UM.USERNAME = UA.USERNAME
    AND
        UM.USERNAME = :username
    AND
        UM.DB_NAME = :db_name