GRANT ALTER ANY PROCEDURE TO :username
GRANT ALTER ANY ROLE TO :username
GRANT ALTER ANY TABLE TO :username
GRANT ALTER SESSION TO :username
GRANT ALTER TABLESPACE TO :username
GRANT ALTER USER TO :username
GRANT ANALYZE ANY TO :username
GRANT CREATE ANY CONTEXT TO :username
GRANT CREATE ANY DIRECTORY TO :username
GRANT CREATE ANY PROCEDURE TO :username
GRANT CREATE ANY SYNONYM TO :username
GRANT CREATE ANY TABLE TO :username
GRANT CREATE ANY TYPE TO :username
GRANT CREATE ANY VIEW TO :username
GRANT CREATE DATABASE LINK TO :username
GRANT CREATE LIBRARY TO :username
GRANT CREATE MATERIALIZED VIEW TO :username
GRANT CREATE PROCEDURE TO :username
GRANT CREATE PUBLIC DATABASE LINK TO :username
GRANT CREATE PUBLIC SYNONYM TO :username
GRANT CREATE ROLE TO :username
GRANT CREATE SEQUENCE TO :username
GRANT CREATE SESSION TO :username
GRANT CREATE SYNONYM TO :username
GRANT CREATE TABLE TO :username
GRANT CREATE TRIGGER TO :username
GRANT CREATE TYPE TO :username
GRANT CREATE USER TO :username
GRANT CREATE VIEW TO :username
GRANT DELETE ANY TABLE TO :username
GRANT DROP ANY PROCEDURE TO :username
GRANT DROP ANY ROLE TO :username
GRANT DROP ANY SYNONYM TO :username
GRANT DROP ANY TABLE TO :username
GRANT DROP ANY VIEW TO :username
GRANT DROP USER TO :username
GRANT EXECUTE ANY PROCEDURE TO :username
GRANT EXECUTE ANY TYPE TO :username
GRANT INSERT ANY TABLE TO :username
GRANT QUERY REWRITE TO :username
GRANT SELECT ANY DICTIONARY TO :username
GRANT SELECT ANY SEQUENCE TO :username
GRANT SELECT ANY TABLE TO :username
GRANT UPDATE ANY TABLE TO :username