GRANT CREATE SESSION TO :username
GRANT CREATE TABLE TO :username 
GRANT CREATE PROCEDURE TO :username  
GRANT CREATE VIEW TO :username  
GRANT DELETE ANY TABLE TO :username  
GRANT INSERT ANY TABLE TO :username 
GRANT SELECT ANY TABLE TO :username 
GRANT UPDATE ANY TABLE TO :username 
GRANT SELECT ANY SEQUENCE TO :username 
GRANT EXECUTE ANY PROCEDURE TO :username 
GRANT CREATE ANY PROCEDURE TO :username 
GRANT DROP ANY PROCEDURE TO :username 
GRANT EXECUTE ANY PROCEDURE TO :username 
GRANT CREATE ANY TABLE TO :username 
GRANT DROP ANY TABLE TO :username 
GRANT SELECT ANY TABLE TO :username 
GRANT CREATE ANY CONTEXT TO :username 
GRANT ALTER SESSION TO :username 
GRANT ANALYZE ANY TO :username 
GRANT CREATE ANY SYNONYM TO :username 
GRANT CREATE ANY TYPE TO :username 
GRANT CREATE DATABASE LINK TO :username 
GRANT CREATE LIBRARY TO :username  
GRANT CREATE MATERIALIZED VIEW TO :username 
GRANT CREATE PUBLIC DATABASE LINK TO :username 
GRANT CREATE PUBLIC SYNONYM TO :username 
GRANT CREATE SEQUENCE TO :username 
GRANT CREATE SYNONYM TO :username 
GRANT CREATE TRIGGER TO :username 
GRANT DROP ANY SYNONYM TO :username 
GRANT EXECUTE ANY TYPE TO :username 
GRANT QUERY REWRITE TO :username 